const products = [
    {
        id:1,
        name: 'S-Prank Blossom Sparkles',
        brand: 'Diesel',
        category: 'Topwear',
        size: 'S,L,M,XL,XXL',
        color: 'Pink',
        fabric: 'cotton',
        producttype: 'Gown',
        price: 5999,
        imagename: 'pr1.jpg',
        objModelName: 'pr1.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:2,
        name: 'S-Prank Jacket Shirt',
        brand: 'Diesel',
        category: 'Topwear',
        size: 'S,L,M,XL,XXL',
        color: 'Grey',
        fabric: 'cotton',
        producttype: 'shirts',
        price: 5499,
        imagename: 'pr2.jpg',
        objModelName: 'pr2.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:3,
        name: 'Netplay Red Wine Gown',
        brand: 'Diesel',
        category: 'Topwear',
        size: 'L,M,XL',
        color: 'Red',
        fabric: 'Synthetic',
        producttype: 'Gown',
        price: 7499,
        imagename: 'pr3.jpg',
        objModelName: 'pr3.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:4,
        name: 'Drake Floral Gown',
        brand: 'Diesel',
        category: 'Topwear',
        size: 'L',
        color: 'Tan',
        fabric: 'Silk',
        producttype: 'Clothing',
        price: 4999,
        imagename: 'pr4.jpg',
        objModelName: 'pr4.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:5,
        name: 'Chanal leather Vanity',
        brand: 'Chanal',
        category: 'Accessories',
        size: 'os',
        color: 'Red,Tan,Beige',
        fabric: 'leather',
        producttype: 'wallet',
        price: 29999,
        imagename: 'pr5.jpg',
        objModelName: 'pr5.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:6,
        name: 'Diesel Mega Cheif Watch',
        brand: 'Diesel',
        category: 'Accessories',
        size: 'os',
        color: 'Black,Tan,Beige',
        fabric: 'leather',
        producttype: 'Watch',
        price: 19900,
        imagename: 'pr6.jpg',
        objModelName: 'pr6.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:7,
        name: 'Nike Pro Run Shoe',
        brand: 'Diesel',
        category: 'Accessories',
        size: 'os',
        color: 'Black,Tan,Beige',
        fabric: 'Mix',
        producttype: 'apparels',
        price: 9999,
        imagename: 'pr7.jpg',
        objModelName: 'pr7.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
    {
        id:8,
        name: 'Diesel Turqiose Nectar',
        brand: 'Diesel',
        category: 'Gown',
        size: 'os',
        color: 'Black,Tan,Beige',
        fabric: 'leather',
        producttype: 'Clothing',
        price: 4999,
        imagename: 'pr8.jpg',
        objModelName: 'pr8.glb',
        description: 'Slim style with a clean construction and essential details. This versatile jean features a comfortable silhouette, finished with a zip fly. The fabric is made using 22% certified recycled cotton, reducing the use of virgin resources. Crafted from denim with partially recycled fibres and a hint of stretch. It features a medium blue wash with a classic, subtly lived-in look.',
        details: 'Material:99%Cotton 1%Elastane-Spandex, Color:Blue,Occasion:Casual Wear,Fit: Slim,Waist: Mid Rise,Closure: Zip Fly',
        otherdetails:'Customer Support Details: Support Number: 022- 48930102, Support Email: support@dieselindia.com,Marketed And Imported By: Diesel Fashion India Reliance Pvt. Ltd., 8th Floor, Maker Tower E, Cuffe Parade, Mumbai, Maharashtra, 400005.,Net Quantity: 1 N,Country Of Origin: Mauritius,Name Of Commodity: Jeans,Style Code: A03558 0NFAJ',
    },
];

export default products;